### ISSUE TITLE
UI Recommendations

### ISSUE THREAD

**Issue by Williano** [abhay-s-rawat/simple_poll#2]
Just some UI recommendations

1. Please can we move the "End Time" of the poll to the end just like the image attached? Below is the code where I change it alignment to spaceBetween
2. 
![Inkedpoll ui_LI](https://user-images.githubusercontent.com/19711677/136625417-e67ce14d-48cf-41a9-8fc6-9b4cfeb7ba39.jpg)

`return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween ,
      children: [
        Flexible(
          flex: 2,
          child: Text(
            model.totalPolls.toString() +
                ' ${polls_translation[languageCode]!}',
            overflow: TextOverflow.ellipsis,
            style: TextStyle(
              fontSize: 12,
              color: Colors.grey,
            ),
          ),
        ),

        ),
        Flexible(
          flex: 2,
          child: Text(
            model.endTime!.isBefore(DateTime.now().toUtc())
                ? polling_ended_translation[languageCode]!
                : '${ends_translation[languageCode]!}: ' +
                    timeago.format(
                      model.endTime!,
                      allowFromNow: true,
                      locale: languageCode,
                    ),
            overflow: TextOverflow.ellipsis,
            style: TextStyle(
              fontSize: 12,
              color: Colors.grey,
            ),
          ),
        ),

        /// This checks if post is editable and user has selected an option.
        /// If [model.editablePoll] evaluates to tue and [model.hasVoted] evaluates to true an 'undo' button will show up which on pressed will remove the option selection and lets user select an option again.
        /// If poll time expires undo button will not be visible.
        if ((model.editablePoll == true) &&
            (model.hasVoted == true) &&
            (model.endTime!.toUtc().isAfter(DateTime.now().toUtc()))) ...[
          Text(
            ' • ',
            overflow: TextOverflow.ellipsis,
            style: TextStyle(
              fontSize: 14,
              color: Colors.grey,
            ),
          ),
          Flexible(
            flex: 1,
            child: GestureDetector(
              child: Text(
                undo_poll_translation[languageCode]!,
                overflow: TextOverflow.ellipsis,
                style: TextStyle(
                  color: Theme.of(context).primaryColor,
                  fontSize: 13,
                ),
              ),
              onTap: () {
                onUndo();
              },
            ),
          ),
        ]
      ],
    );`

**Comment by Williano** [comment]
2. Please once the Polls ends, can we show "Final results" at in place of the "end time" just like the image attached? I can make it a PR if you want.

![Screen-Shot-2015-11-23-at-22 28 44](https://user-images.githubusercontent.com/19711677/136626150-3565514e-1983-4d4d-bf65-c1853760b867.png)

**Comment by abhay-s-rawat** [comment]
It already shows results when user polled or poll ends.

**Comment by abhay-s-rawat** [comment]
Actually for the UI part I recommend making changes to your local copy of this project ie: copy the files of this project.
Actually there is less space in the bottom status part so to make it run and look even in small screens I made it like it. Most of the text which is unknown can overflow (time left translation) and to tackle it I made it inline.

**Comment by Williano** [comment]
Great 👍… Thank you
